[package]
description = "A JIT Compiler for Neural Network Inference"
edition = "2018"
homepage = "https://github.com/HULKs/compiled-nn-rs"
license = "MIT"
name = "compiled-nn"
version = "0.6.0"

[dependencies]
compiled-nn-bindings = {path = "compiled-nn-bindings", version = "0.6.0"}
